USER_NAME = ''
GIT_SOURCE_LINK = ''
PASSWORD = ''

NEW_MERGE_REQUEST_PATTERN = ''
EPE_TRACE_PATTERN = ''

SUBMIT_TEXTS = ['submit merge request','submit']
CASES_TO_IGNORE = ['compare branches and continue']

MERGE_REQUEST_HEADERS= 'SOURCE_BRANCH\tDESTINATION_BRANCH\tBRANCH_PRESENCE\tCOMMIT_MESSAGE_MATCH\tMERGE_REQUEST_STATUS\tMERGE_REQUEST_ID\n'
AUTO_MERGE_REQUEST_LOG = 'G:\\Ajith\\OtherFiles\\GITAutomation\\AUTO_RAISED_MERGE_REQUEST_LOG.txt'
# AUTO_MERGE_REQUEST_LOG = 'AUTO_RAISED_MERGE_REQUEST_LOG.txt'

AUTO_MERGE_REQUEST_FILE = 'Auto_raised merge_requests.txt'

# AUTO_EPE_TRACE_LOG = 'AUTO_EPE_TRACE_LOG.txt'
AUTO_EPE_TRACE_LOG = 'G:\\Ajith\\OtherFiles\\GITAutomation\\AUTO_EPE_TRACE_LOG.txt'
AUTO_EPE_TRACE_FILE = 'Auto_epe_trace.txt'
EPE_TRACE_HEADERS ='NO\tTOTAL_RECORDS\tEPE-ID\tEPE_TITLE\tMERGE_REQ_ID\tAUTHOR\tTARGET_BRANCH\tSTATUS\tPERIOD\n'


COMMIT_MESSAGE_PATTERN = '[<epe_id>]'