USERNAME = ''
PASSWORD = ''

RTRACK_LOG_FILE = 'RTRACK_LOG.txt'
			
RTRACK_HEADERS = 'TOTAL_IDS\tSOURCE_ID\tDEFECT_STATUS\tASSIGNEE\tCOMMENTS\tDEFECT_ID1\tSTATUS1\tDEFECT_ID2\tSTATUS2\tDEFECT_ID3\tSTATUS3\tDEFECT_ID4\tSTATUS4\n'