# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BhavCopyDemo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BhavCopy(object):
    def setupUi(self, BhavCopy):
        BhavCopy.setObjectName("BhavCopy")
        BhavCopy.resize(750, 552)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AppLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BhavCopy.setWindowIcon(icon)
        self.GetBhavCopy = QtWidgets.QPushButton(BhavCopy)
        self.GetBhavCopy.setGeometry(QtCore.QRect(170, 370, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.GetBhavCopy.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.GetBhavCopy.setFont(font)
        self.GetBhavCopy.setObjectName("GetBhavCopy")
        self.startdate_label = QtWidgets.QLabel(BhavCopy)
        self.startdate_label.setGeometry(QtCore.QRect(170, 73, 110, 30))
        self.startdate_label.setObjectName("startdate_label")
        self.comp_wise_radiobtn = QtWidgets.QRadioButton(BhavCopy)
        self.comp_wise_radiobtn.setGeometry(QtCore.QRect(320, 160, 161, 31))
        self.comp_wise_radiobtn.setObjectName("comp_wise_radiobtn")
        self.bvcp_type_label = QtWidgets.QLabel(BhavCopy)
        self.bvcp_type_label.setGeometry(QtCore.QRect(170, 160, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bvcp_type_label.setFont(font)
        self.bvcp_type_label.setObjectName("bvcp_type_label")
        self.date_wise_radiobtn = QtWidgets.QRadioButton(BhavCopy)
        self.date_wise_radiobtn.setGeometry(QtCore.QRect(320, 180, 121, 31))
        self.date_wise_radiobtn.setObjectName("date_wise_radiobtn")
        self.enddate_edit = QtWidgets.QDateEdit(BhavCopy)
        self.enddate_edit.setGeometry(QtCore.QRect(310, 110, 110, 22))
        self.enddate_edit.setObjectName("enddate_edit")
        self.enddate_label = QtWidgets.QLabel(BhavCopy)
        self.enddate_label.setGeometry(QtCore.QRect(170, 112, 101, 21))
        self.enddate_label.setObjectName("enddate_label")
        self.startdate_edit = QtWidgets.QDateEdit(BhavCopy)
        self.startdate_edit.setGeometry(QtCore.QRect(310, 80, 110, 22))
        self.startdate_edit.setObjectName("startdate_edit")
        self.output_folder_label = QtWidgets.QLabel(BhavCopy)
        self.output_folder_label.setGeometry(QtCore.QRect(170, 230, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.output_folder_label.setFont(font)
        self.output_folder_label.setObjectName("output_folder_label")
        self.browse_btn = QtWidgets.QPushButton(BhavCopy)
        self.browse_btn.setGeometry(QtCore.QRect(570, 280, 75, 23))
        self.browse_btn.setObjectName("browse_btn")
        self.pathchooser_edit = QtWidgets.QLineEdit(BhavCopy)
        self.pathchooser_edit.setGeometry(QtCore.QRect(300, 240, 401, 20))
        self.pathchooser_edit.setObjectName("pathchooser_edit")
        self.progressBar = QtWidgets.QProgressBar(BhavCopy)
        self.progressBar.setGeometry(QtCore.QRect(170, 310, 351, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(BhavCopy)
        QtCore.QMetaObject.connectSlotsByName(BhavCopy)

    def retranslateUi(self, BhavCopy):
        _translate = QtCore.QCoreApplication.translate
        BhavCopy.setWindowTitle(_translate("BhavCopy", "Form"))
        self.GetBhavCopy.setText(_translate("BhavCopy", "Download Bhav Copy"))
        self.startdate_label.setText(_translate("BhavCopy", "Choose Start Date"))
        self.comp_wise_radiobtn.setText(_translate("BhavCopy", "Company wise files"))
        self.bvcp_type_label.setText(_translate("BhavCopy", "Bhav copy type"))
        self.date_wise_radiobtn.setText(_translate("BhavCopy", "Date wise files"))
        self.enddate_edit.setDisplayFormat(_translate("BhavCopy", "dd-MM-yyyy"))
        self.enddate_label.setText(_translate("BhavCopy", "Choose End Date"))
        self.startdate_edit.setDisplayFormat(_translate("BhavCopy", "dd-MM-yyyy"))
        self.output_folder_label.setText(_translate("BhavCopy", "Output Folder"))
        self.browse_btn.setText(_translate("BhavCopy", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BhavCopy = QtWidgets.QWidget()
    ui = Ui_BhavCopy()
    ui.setupUi(BhavCopy)
    BhavCopy.show()
    sys.exit(app.exec_())
