# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BhavCopyDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edt_startdate = QtWidgets.QDateEdit(self.centralwidget)
        self.edt_startdate.setGeometry(QtCore.QRect(310, 50, 110, 22))
        self.edt_startdate.setObjectName("edt_startdate")
        self.edt_enddate = QtWidgets.QDateEdit(self.centralwidget)
        self.edt_enddate.setGeometry(QtCore.QRect(310, 80, 110, 22))
        self.edt_enddate.setObjectName("edt_enddate")
        self.GetBhavCopy = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.generate_bhav_copy(start_date = self.edt_startdate.text(), 
                                                                                                        end_date = self.edt_enddate.text() ,
                                                                                                        splits=[self.get_bhav_type()]))
        self.GetBhavCopy.setGeometry(QtCore.QRect(170, 230, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.GetBhavCopy.setPalette(palette)
        
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.GetBhavCopy.setFont(font)
        self.GetBhavCopy.setObjectName("GetBhavCopy")
        self.lbl_str_dt = QtWidgets.QLabel(self.centralwidget)
        self.lbl_str_dt.setGeometry(QtCore.QRect(170, 43, 110, 30))
        self.lbl_str_dt.setObjectName("lbl_str_dt")
        self.lbl_end_dt = QtWidgets.QLabel(self.centralwidget)
        self.lbl_end_dt.setGeometry(QtCore.QRect(170, 82, 101, 21))
        self.lbl_end_dt.setObjectName("lbl_end_dt")
        self.rdb_comp_wise = QtWidgets.QRadioButton(self.centralwidget)
        self.rdb_comp_wise.setGeometry(QtCore.QRect(320, 130, 161, 31))
        self.rdb_comp_wise.setObjectName("rdb_comp_wise")
        self.rdb_comp_wise.setChecked(True)
        self.rdb_date_wise = QtWidgets.QRadioButton(self.centralwidget)
        self.rdb_date_wise.setGeometry(QtCore.QRect(320, 150, 121, 31))
        self.rdb_date_wise.setObjectName("rdb_date_wise")
        self.lbl_bvcp_type = QtWidgets.QLabel(self.centralwidget)
        self.lbl_bvcp_type.setGeometry(QtCore.QRect(170, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_bvcp_type.setFont(font)
        self.lbl_bvcp_type.setObjectName("lbl_bvcp_type")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_bhav_type(self): # company wise / date wise
        if self.rdb_comp_wise.isChecked()==True:
            print('company_wise')
            return 'company_wise'
        elif self.rdb_date_wise.isChecked()==True:
            print('date_wise')
            return 'date_wise'
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GetBhavCopy.setText(_translate("MainWindow", "Download Bhav Copy"))
        self.lbl_str_dt.setText(_translate("MainWindow", "Choose Start Date"))
        self.lbl_end_dt.setText(_translate("MainWindow", "Choose End Date"))
        self.rdb_comp_wise.setText(_translate("MainWindow", "Company wise files"))
        self.rdb_date_wise.setText(_translate("MainWindow", "Date wise files"))
        self.lbl_bvcp_type.setText(_translate("MainWindow", "Bhav copy type"))
    def generate_bhav_copy(self,start_date ,end_date,splits):
        print('generate_bhav_copy called')
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
