# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DropDown-XOR-Applications.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# this XOR gate function is pretty intresting man.... 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(360, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Output = QtWidgets.QTextEdit(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(580, 130, 141, 71))
        self.Output.setObjectName("Output")
        self.Output.setFont(font)
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(290, 280, 161, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Submit.setFont(font)
        self.Submit.setObjectName("Submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # adding additional values to the combo box... and 
        # making default indexes..
        
        # self.comboBox.addItem('Hello')
        # index = self.comboBox.findText('Hello',QtCore.Qt.MatchFixedString)
        # self.comboBox.setCurrentIndex(index)
        # self.comboBox.setCurrentIndex(2)
        
        
        self.Submit.clicked.connect(self.disp_res)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "XOR"))
        self.label_2.setText(_translate("MainWindow", " ="))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        
    def disp_res(self,res):
        x = int(self.comboBox.currentText())
        y = int(self.comboBox_2.currentText())
        xor_res = (x and not y) or (not x and y)
        if xor_res == True:
            xor_res = 1
        else:
            xor_res = 0 
            
        self.Output.setText(str(xor_res))
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
