# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserPwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(783, 562)
        self.password_edit = QtWidgets.QLineEdit(LoginForm)
        self.password_edit.setGeometry(QtCore.QRect(280, 130, 171, 31))
        self.password_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.user_edit = QtWidgets.QLineEdit(LoginForm)
        self.user_edit.setGeometry(QtCore.QRect(280, 90, 171, 31))
        self.user_edit.setObjectName("user_edit")
        self.password_label = QtWidgets.QLabel(LoginForm)
        self.password_label.setGeometry(QtCore.QRect(110, 120, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.login_button = QtWidgets.QPushButton(LoginForm)
        self.login_button.setGeometry(QtCore.QRect(280, 200, 150, 30))
        self.login_button.setObjectName("login_button")
        self.username_label = QtWidgets.QLabel(LoginForm)
        self.username_label.setGeometry(QtCore.QRect(110, 70, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.checkBox = QtWidgets.QCheckBox(LoginForm)
        self.checkBox.setGeometry(QtCore.QRect(280, 176, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.password_label.setText(_translate("LoginForm", "Password"))
        self.login_button.setText(_translate("LoginForm", "LOGIN"))
        self.username_label.setText(_translate("LoginForm", "Username"))
        self.checkBox.setText(_translate("LoginForm", "Receive news letters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec_())
