from ms_login import *
# HOME PAGE
#url='https://myinspire.microsoft.com/page/attendeenetworking?p1=eyJzcGVha2VyIjpbXSwidGltZXNsb3QiOltdLCJkYXkiOltdLCJyb29tIjpbXSwicGFnZW51bWJlciI6MSwiY2F0ZWdvcmllcyI6e30sImtleXdvcmQiOiIifQ%3D%3D'
url='https://myinspire.microsoft.com/page/attendeenetworking?p1=eyJzcGVha2VyIjpbXSwidGltZXNsb3QiOltdLCJkYXkiOltdLCJyb29tIjpbXSwicGFnZW51bWJlciI6MSwiY2F0ZWdvcmllcyI6eyJyZWdpc3RyYW50IHRpdGxldGhhdGRlc2NyaWJlc3lvdSI6WyJiNzE0MzUyZC1jZjhhLTQ1YzQtOWFhYi04ZWZjNDc5MTI0NWYiLCJjMmRlOGMxZS04YzQ3LTQwMzMtYTk5OC00ZmUwOWQ5MGVhNDciXX0sImtleXdvcmQiOiIifQ%3D%3D'
ms_login(url)